### ISSUE TITLE
doesn't run on Windows machine

### ISSUE THREAD

**Issue by rspotnitz** [cidetec-energy-storage/cideMOD#2]
**Using Docker and enter into Command Prompt window**

C:\Windows\System32>docker pull cidetec/cidemod
Using default tag: latest
latest: Pulling from cidetec/cidemod
.. 
.. // pulls 
Digest: sha256:2caba9f8c4677fba61259774057d7dbf392c5d3071adcac85c68c1837fa4d403
Status: Downloaded newer image for cidetec/cidemod:latest
docker.io/cidetec/cidemod:latest

**When pull completes, then try to run using this command**

C:\Windows\System32>docker run --name cidemod -ti cidetec/cidemod
fenics@b84c5fefba9a:~$ from cideMOD import CSI, DEFAULTS
from: can't read /var/mail/cideMOD

**Please advise on how to eliminate the error "can't read /var/mail/cideMOD".**

Thank you.

**Comment by cidetec-es** [comment]
You should invoke Python first using `ipython3` or `python3`. You can try to import cideMOD:

```console

$ python3 -c "import cideMOD"

```

If you are following the examples of the [Getting Started](https://cidemod.readthedocs.io/en/latest/usage.html) section, I suggest you save the commands in a python script (e.g. myfirstrun.py) and then execute it:

```console

$ python3 myfirstrun.py

```

We are working on the documentation currently, and cideMOD v0.2 will be available soon. Unfortunately, the docker image of cideMOD is not up to date, so I recommend you to update cideMOD. Open the container bash and type the following:


```console

$ pip uninstall cideMOD

$ git clone https://github.com/cidetec-energy-storage/cideMOD.git /home/cideMOD

$ pip install /home/cideMOD/.

```

To test if the installation is complete, run a simple test:

```console

pytest -m "Chen and p2d and validation"

```

**Comment by rspotnitz** [comment]
Thanks for your quick response.
In Docker, I selected the cidemod container and clicked the Action "Open in terminal".  In the terminal, I typed the 3 commands from your message, and then tried the test.  Got the following error:


========================= ERRORS==========================================
___________________ ERROR collecting cideMOD/tests/test_Ai_2020.py ________________________________________________
ImportError while importing test module '/home/fenics/cideMOD/tests/test_Ai_2020.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/home/fenics/shared/OS_PXD/tests/test_Ai_2020.py:6: in <module>
    ???
E   ImportError: cannot import name 'StressProblem'


I will wait for cideMOD v0.2  and then try again.
Thanks again.
